# -*- coding: utf-8 -*-
"""Copy of Gla_ML_Session1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKyXwE8LoQ9srTRkW2UeLn0j_Red0y7f

Calculate the avg marks and prin t class fialed or passed is the avg is 50 or above
"""



marks = [45, 60, 72, 38, 90]

total = 0

for i in range(len(marks) - 1):
    total += marks[i]

average = total / len(marks)

if average > 50:
    print("Class passed")
else:
    print("Class failed")

print("Average:", average)

import pandas as pd

data = {
    "student_id": [101, 102, 103, 104, 105, 106],
    "attendance_percent": [92, 67, 81, 45, 74, 88],
    "assignment_score": [18, 12, 15, 8, 14, 19],
    "quiz_score": [72, 48, 65, 30, 55, 80],
    "lab_completed": [True, False, True, False, True, True]
}

df = pd.DataFrame(data)

df

df.shape

df['performance'] = pd.cut(
    df['total_score'],
    bins=[-float('inf'), 50, 75, float('inf')],
    labels=['Poor', 'Average', 'Excellent']
)

df.head()

df.info()

df.describe()

df['total_score'] = df['assignment_score'] + df['quiz_score']
df

df['eligible'] = (
    (df['attendance_percent'] >= 75) &
    (df['total_score'] >= 70) &
    (df['lab_completed'])
)
df

eligible_students = df[df["eligible"] == True]
eligible_students

print(df.columns)

"""# 1.Avg Score"""

df['average_score'] = (
    df['assignment_score'] +
    df['quiz_score'] +
    df['total_score']
) / 3

"""2. Attendance Category"""

df['attendance_category'] = pd.cut(
    df['attendance_percent'],
    bins=[0, 60, 80, 100],
    labels=['Low', 'Medium', 'High']
)

"""3. Performance Category"""

df['performance'] = pd.cut(
    df['total_score'],
    bins=[0, 50, 75, 100],
    labels=['Poor', 'Average', 'Excellent']
)

import matplotlib.pyplot as plt

plt.hist(df['attendance_percent'], bins=10)
plt.title('Attendance Distribution')
plt.xlabel('Attendance %')
plt.ylabel('Number of Students')
plt.show()

plt.hist(df['assignment_score'], bins=10)
plt.title('Assignment Score Distribution')
plt.xlabel('Score')
plt.ylabel('Count')
plt.show()

plt.scatter(df['quiz_score'], df['total_score'])
plt.title('Quiz Score vs Total Score')
plt.xlabel('Quiz Score')
plt.ylabel('Total Score')
plt.show()

df['performance'].value_counts().plot(kind='bar')

plt.title('Performance Categories')
plt.xlabel('Category')
plt.ylabel('Students')
plt.show()

df['eligible'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title('Eligibility Distribution')
plt.ylabel('')
plt.show()

plt.scatter(df['lab_completed'], df['total_score'])

plt.title('Labs Completed vs Total Score')
plt.xlabel('Labs Completed')
plt.ylabel('Total Score')
plt.show()